import {
    Box,
    Text,
    Image,
    Table,
    TableCaption,
    TableContainer,
    Tbody,
    Td,
    Tfoot,
    Th,
    Thead,
    Tr,
    Button
} from '@chakra-ui/react'
import type {NextPage} from 'next'
import Head from 'next/head'
import {Header} from '../components/Header'
import styles from '../styles/Home.module.css'
import {useState} from "react";

const Home: NextPage = () => {

    const hello_return = () => {
        console.log('hello')
    }

    const changeText = () => {
        const textElement = document.getElementById('text')
        textElement!.innerText = 'Hello World'
    }

    const [text, setText] = useState('beforeText')

    const peopleArray = ['zaki', 'shoma', 'than', 'trieu']

    return (
        <div className={styles.container}>
            <Head>
                <title>Create God App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Header times='Unko'></Header>
            <Box
                mt={'100px'}
            >
                <Button
                    onClick={() => {
                        setText('hello')
                    }}
                >
                    button
                </Button>
                <p>{text}</p>
            </Box>
            {peopleArray.map((person, index) => {
                return <p key={index}>{person}</p>
            })}
            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg"
                               alt="Vercel Logo"
                               width={72}
                               height={16}/>
                    </span>
                </a>
            </footer>
        </div>
    )
}

export default Home
