import {
    Box,
    Text,
    Image,
    Table,
    TableCaption,
    TableContainer,
    Tbody,
    Td,
    Tfoot,
    Th,
    Thead,
    Tr,
    Button
} from '@chakra-ui/react'
import type {NextPage} from 'next'
import Head from 'next/head'
import {Header} from '../components/Header'
import styles from '../styles/Home.module.css'
import {useState} from "react";

const Home: NextPage = () => {

    const hello_return = () => {
        console.log('hello')
    }

    const changeText = () => {
        const textElement = document.getElementById('text')
        textElement!.innerText = 'Hello World'
    }

    const [text, setText] = useState('beforeText')

    const peopleArray = [{name: 'zaki', age: 28}, {name: 'shoma', age: 26}, {name: 'than', age: 29}, {
        name: 'trieu',
        age: 27
    }]

    return (
        <div className={styles.container}>
            <Head>
                <title>Create God App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Header times='Unko'></Header>
            <Box
                mt={'100px'}
            >
                <Button
                    onClick={() => {
                        setText('hello')
                    }}
                >
                    button
                </Button>
            </Box>
            <Box>
                <Box
                    p={'10px'}
                    gap={'10px'}
                    display={'flex'}
                >
                    {peopleArray.map((personInfo, index) => {
                        return (
                            <Box
                                p={'10px'}
                                border={'1px solid black'}
                                borderRadius={'5px'}
                                key={index}
                                gap={'10px'}
                                boxShadow={'md'}
                            >
                                <Text>名前:{personInfo.name}</Text>
                                <Text>年齢:{personInfo.age}</Text>
                            </Box>
                        )
                    })}
                </Box>
            </Box>
            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg"
                               alt="Vercel Logo"
                               width={72}
                               height={16}/>
                    </span>
                </a>
            </footer>
        </div>
    )
}

export default Home
